apiVersion:  apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: migrator
spec:
  replicas: 0
  selector:
    matchLabels:
      name: helm-demo
      release: v1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: helm-demo
        release: v1
    spec:
      containers:
      - image: smithrh/public-tests:ep-migrator-v1
        name: migrator
        resources: {}
      restartPolicy: Always
status: {}
