apiVersion:  apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      name: helm-demo
      release: v1  
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: helm-demo
        release: v1
    spec:
      containers:
      - env:
        - name: RABBITMQ_DEFAULT_PASS
          value: yourStrong(!)Password
        - name: RABBITMQ_DEFAULT_USER
          value: admin
        - name: RABBITMQ_DEFAULT_VHOST
          value: /
        - name: RABBITMQ_ERLANG_COOKIE
          value: RSPAZZFQBLQOZDAEOCCX
        image: rabbitmq:3-management
        name: rabbitmq
        ports:
        - containerPort: 15672
        - containerPort: 5672
        resources: {}
      hostname: rabbitmq
      restartPolicy: Always
status: {}
